### ISSUE TITLE
关于广告位的对应关系

### ISSUE THREAD

**Issue by JiphuTzu** [lilili87222/baidu-ssp-ane#1]
在百度的代码位中分别有横幅、开屏、插屏、积分墙、应用推荐墙五类，请问在ANE中是如何对应的呢？
我测试了一下，大概知道横幅使用showBanner，开屏的showInterstitial(但是大小不太正确)，比如插屏等的广告是怎么显示的呢？

**Comment by lilili87222** [comment]
插屏和全屏是统一的，积分墙和应用墙不支持

**Comment by JiphuTzu** [comment]
还有一个问题，全屏广告好像没有5秒钟自动消失。插屏的尺寸貌似只比全屏的小一点点。

**Comment by JiphuTzu** [comment]
全屏广告好像没有5秒钟自动消失。插屏的尺寸貌似只比全屏的小一点点。还有一个问题，断网的情况下，插屏使用cacheInterstitial()方法，第二次就没有onInterstitialFailedReceive消息了。

**Comment by lilili87222** [comment]
百度的全屏插屏是不区分的，无论哪种，他都会混着展示。插屏会出全屏的，全屏也会出插屏的。具体事件的抛出是sdk内部控制的，什么时候有什么时候没有ane没法控制的。
